# -*- coding: utf-8 -*-
"""Fase 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEijB3Ij123C_q4Y-Afrd-YlwpkJbVy6
"""

import pandas as pd
import joblib
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.compose import ColumnTransformer

def ejecutar_fase_2(ruta_input="spam_limpio.csv"):
    print("Iniciando Fase 2: Configuración de Vectorización y Partición...")

    # 1. Ingestión de datos limpios
    df = pd.read_csv(ruta_input)

    # Prevención de errores: si la limpieza de Fase 1 dejó celdas de texto vacías,
    # pandas las lee como NaN. Debemos convertirlas a strings vacíos.
    df['texto_limpio'] = df['texto_limpio'].fillna('')

    # 2. Separar Variables Independientes (X) y Objetivo (y)
    X = df[['texto_limpio', 'num_caracteres', 'num_mayusculas', 'num_digitos']]
    y = df['label_num']

    # 3. Partición Train / Test (80% / 20%)
    # stratify=y es obligatorio para asegurar que el 13% de spam se mantenga en ambas partes
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # 4. Construcción del Preprocesador Matemático (El "Traductor")
    # ColumnTransformer permite aplicar reglas distintas a columnas distintas en paralelo
    preprocesador = ColumnTransformer(
        transformers=[
            # Aplica TF-IDF con un vocabulario máximo de 3000 palabras a la columna de texto
            ('texto', TfidfVectorizer(max_features=3000), 'texto_limpio'),
            # Aplica una escala de 0 a 1 a las columnas numéricas para que no dominen a las palabras
            ('numeros', MinMaxScaler(), ['num_caracteres', 'num_mayusculas', 'num_digitos'])
        ]
    )

    # 5. Exportación de los datos partidos (para la Fase 3)
    X_train.to_csv('X_train.csv', index=False)
    X_test.to_csv('X_test.csv', index=False)
    y_train.to_csv('y_train.csv', index=False)
    y_test.to_csv('y_test.csv', index=False)

    # 6. Exportación de la estructura del preprocesador
    joblib.dump(preprocesador, 'preprocesador_base.joblib')

    print("Fase 2 completada.")
    print(f"Dimensiones de entrenamiento: {X_train.shape[0]} filas.")
    print(f"Dimensiones de prueba: {X_test.shape[0]} filas.")